### ISSUE TITLE
SSLHandshake error in Piper

### ISSUE THREAD

**Issue by noellowry** [SAP/devops-cm-client#48]
I am trying to use the transportRequestUploadFile step in Piper but I get error:

`Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

How can add the required certs to image?
I tried to create image from ppiper/cm-client, add certs and try that. But it did not work.
Can I disable the check even?

**Comment by marcusholl** [comment]
@noellowry : 

Having a valid trust store something like sketched below worked for me in the past:

```
docker run -v /path/to/truststore/on/docker/host:/path/to/truststore/inside/docker/container \
           --env CMCLIENT_OPTS="-Djavax.net.ssl.trustStore=/path/to/truststore/inside/docker/container" \
           <label> cmclient -t <backendType> \
                            -e <serviceEndpoint> \
                            -u <serviceUser> \
                            -p <password>
                          <SUBCOMMAND> [SUBCOMMAND_OPTS]
```

> Can I disable the check even?

Found [this](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html). Seems to be related, maybe that helps:

``` -Dcom.sun.net.ssl.checkRevocation=false```

For productive environments I can't recommand this.

**Comment by noellowrysap** [comment]
@marcusholl thank you for the info.
I've tried creating a keystore with certs on an image and using that but it did not work.
And even setting the variable `CMCLIENT_OPTS="-Dcom.sun.net.ssl.checkRevocation=false" `does not work.
I keep getting the error when trying to run on my JaaS.

If I login locally using eg
`docker run -it ppiper/cm-client`

And then set variable:
`export CMCLIENT_OPTS="-Dcom.sun.net.ssl.checkRevocation=false"`
The cmclient command will run.

Really can't see why the same steps would not run in pipeline

**Comment by marcusholl** [comment]
@maxx1e : due to vacation on my end I did not see that earlier. I will try to reproduce your issue locally.

**Comment by maxx1e** [comment]
Well the issue was fixed from my side with the following solution: 

- Create own Docker image based on debian:stable-slim
- Put inside of the image openjdk-11-jre-headless and cm_client
- Download required certificate chain from the browser
- pass certificates to during build phase via ARG (do not forget to COPY them inside): 
```
ARG ROOT_CERT="root.cer"
ARG INTER_CERT="inter.cer"
ARG HOST_CERT="srv.cer"
```
- provide JAVA environment to the certificates truststore place: 
`ENV CMCLIENT_OPTS="-Djavax.net.ssl.trustStore=/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts"`
- add certs to the keystore: 
`keytool -import -trustcacerts -noprompt -keystore /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -storepass changeit -alias "${HOST_CERT%.*}" -file "${CM_USER_HOME}/${HOST_CERT}" && \`

Done, now this image can be run as part of pipeline. It will be able to establish connection with no errors.

**Comment by marcusholl** [comment]
@maxx1e : ups, sorry for not responding. TBH I forgot about it. Sorry ...
Thanks a lot for sharing ...
